### ISSUE TITLE
InstructionAttribute IS_PRIVILIGED is misspelled ("privileged")

### ISSUE THREAD

**Issue by williballenthin** [zyantific/zydis-rs#15]
The `InstructionAttributes` bitflag constant `IS_PRIVILIGED` is misspelled; it should be `IS_PRIVILIGED`: https://github.com/zyantific/zydis-rs/blob/1a778406758cbbac5a9f9df834add3f509add006/src/enums/mod.rs#L750

In the C source, the documentation is misspelled, but the symbol name is correctly spelled: https://github.com/zyantific/zydis/blob/356e0e60c1e7e3c9a7002e3ea9b9c6e95de9ca8c/include/Zydis/DecoderTypes.h#L265

![image](https://user-images.githubusercontent.com/156560/49045995-ee929000-f18f-11e8-8434-a9c6caa1eb63.png)

**Comment by th0rex** [comment]
Thanks again, I fixed this in https://github.com/zyantific/zydis-rs/commit/e8338680cacaed391a800298a11e0d3b4b600e1e. I also forwarded this so the doc comment gets fixed.
