### ISSUE TITLE
Windows Kernel support

### ISSUE THREAD

**Issue by carlos-al** [zyantific/zydis-rs#38]
If you try using this library directly in a Windows kernel driveryou'll see five extra imports from Kernel32.dll that shouldn't be there.
![without_flag](https://github.com/zyantific/zydis-rs/assets/8768569/73f12bf3-3926-4355-8d37-725ab6ed3253)

If you look at the Visual Studio solutions in zydis/msvc, you'll see that the ZydisWinKernel solution needs the BufferOverflowK library to build properly.
This can be fixed adding the following line to `build.rs`:
`println!("cargo:rustc-link-lib=BufferOverflowK");`

**Comment by athre0z** [comment]
Resolved in 9e1528cea64e7ce99d7d97e4a1986410e654208a. I also configured `no-stack-protector` to automatically be enabled when `nolibc` feature is enabled.
