### ISSUE TITLE
Update to v2-beta

### ISSUE THREAD

**Issue by tathanhdinh** [zyantific/zydis-rs#7]
Hello all,
Is there any plan to support `zydis v2-beta`? I pulled the `master` branch for `zydis-c`, but `zydis-rs` doesn't compile. I have tried to fix it myself but it is beyond my current knowledge about Rust :(

**Comment by athre0z** [comment]
Yes. We're planning to release the final version of `v2.0.0` in the coming few days and updates of the Rust bindings will follow shortly after.

**Comment by athre0z** [comment]
I updated the bindings to the latest commit on `develop` — all tests passing. Will create a new tag & cargo release once the C final tag is created and the bindings submodule is moved to the tag as well.
